### ISSUE TITLE
Update ee4j Org header

### ISSUE THREAD

**Issue by delabassee** [eclipse-ee4j/ee4j#10]
Right now, there are 2 EE4J GH Org: 'eclipse-ee4j' and 'ee4j'
The ee4j Org header should be updated to reflect the fact that it's a parked Org without any activity; people should go to https://github.com/eclipse-ee4j/ instead.

**Comment by smillidge** [comment]
@waynebeaton @eclipsewebmaster can the Readme for this organisation be changed https://github.com/ee4j/ ?

**Comment by ivargrimstad** [comment]
Done
