### ISSUE TITLE
Logo Poll

### ISSUE THREAD

**Issue by dblevins** [eclipse-ee4j/ee4j#11]
Consider this an informal poll to help with the logo selection process.  This is not a vote.

Add thumbs up to any logos you like.  Feel free to use other emoticons.

## UPDATE March 29th, 2018

Poll is now closed and the official voting is now open!  Cast your vote!  Vote will be closed April 6th.

 - https://t.co/cfxT47xTyQ

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871807-25d69620-2fac-11e8-8c88-6840217fcf77.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871809-32d5c3fa-2fac-11e8-9716-7fd5eb54ae98.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871814-40ac226c-2fac-11e8-978e-66e0bcfb0246.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871815-4a1730bc-2fac-11e8-89dd-85388970d35d.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871830-8746de10-2fac-11e8-8efd-5a7e55e73c52.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871834-9f708176-2fac-11e8-9d73-047b33aca52a.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871848-e9a21dae-2fac-11e8-8eb5-ef117778ffb2.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871850-01cc9df0-2fad-11e8-9622-2a4861f77d30.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871854-1240c396-2fad-11e8-82ee-a21eefc8004a.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871867-41b3b02a-2fad-11e8-8d0d-c1d4a235ab20.png)

**Comment by dblevins** [comment]
![image](https://user-images.githubusercontent.com/94926/37871868-54a62708-2fad-11e8-8c3d-23d7a644c2d9.png)

**Comment by hendrikebbers** [comment]
@dblevins 👍

**Comment by keilw** [comment]
@dblevins Thanks for the shortlist. The bottom one clearly looks too much like the Angular logo.
The sextant and also sail-boat have a bit too little to do with Java, ok maybe the boat, but the logo of JCP EC Member Credit Suisse (not that it would care, I am sure, they have other problems than voting here given their lack of participation in the JCP and things like JavaMoney) https://www.google.de/imgres?imgurl=https://cdnext.credit-suisse.com/corporate/de/media/pictures/_jcr_content/content/pagetabscontainer/tabs/pagetab_1/tabContent/flexiblelist/flexibleListItems/flexiblelistitem/image.revampimg.656.high.jpg/credit-suisse-logo-color.jpg&imgrefurl=https://www.credit-suisse.com/corporate/de/media/pictures.html&h=328&w=656&tbnid=XfO7m1Q4P8uMmM:&tbnh=75&tbnw=151&usg=__c11pBsJNV9pxzJCgbiAI8t4ZcTs%3D&vet=10ahUKEwiv_cGHhIraAhWG3KQKHTtRBMAQ_B0I7wEwDw..i&docid=jyUqXJCXXuRqCM&itg=1&sa=X&ved=0ahUKEwiv_cGHhIraAhWG3KQKHTtRBMAQ_B0I7wEwDw is at least close to it.

I just heard about the [Borromean Rings](https://en.wikipedia.org/wiki/Borromean_rings) in the [last episode of Inspector Lewis](http://www.radiotimes.com/news/2015-11-10/lewis-airs-its-final-episode-but-have-we-really-seen-the-last-of-hathaway/). And I love the similarity of the "twisty knot" like logo. The Lewis episode mentioned something like "if one of them goes away, the whole structure collapses". I find that a perfect analogy for the new way, Jakarta EE is supposed o work under Eclipse :-D

**Comment by DcortezMeleth** [comment]
I'm just wondering if there won't be any legal problems with logo almost identical as Cloud9 have?
But of course it may be just me seeing thing other don't see. :D

Cloud9 logo if anyone wonders how it looks.
<img src="https://user-images.githubusercontent.com/5192048/37965472-828f1f20-31c5-11e8-87fd-d58a353a1d7f.png" width="200">

**Comment by deontologic** [comment]
Sailboat logo is the one! Vibrant gold/navy colors, and enough detail to look sophisticated when blown up on the website. Can't say that for the other designs, which are too simple or abstract. 

Sailing as a theme stands for adventure, beauty, and technical skill; EE4J would benefit from the association.

**Comment by keilw** [comment]
It seems there are 3 favorites. Unless the Borromean Rings have any branding issue (I thought Eclipse legal had already checked the ones here?) I still like them best, but all 3 would do. The sails have no reference to Java or a "J" shape, but it might be a very subtle one to the island of Jakarta, so if that is not too obvious, and Credit Suisse has no issue either, why not.

**Comment by marta-sobon** [comment]
Is it possible to submit a new design to the contest :)?

**Comment by keilw** [comment]
I don't think so, it would make things even more complicated, plus it sounds like one or two design agencies have already been shortlisted and those are their proposals.

**Comment by mfevzikorkutata** [comment]
Hi All,

Our submission has been eliminated. Thank you all the positive voters for us. **Wish success for the rest; wish best for Jakarta EE.**

Actually our submission was not only a CLOUD icon; it contains location and infinity icon in it. We thought to reflect "Sky is the limit for a JakartaEE Developer" and still thinking the same way :)

Eclipse Foundation pointed here (comments in this page) cause of our elimination.

I am putting our submission's evolution. If someone want to use one of them in their open source project just contact to me.

PS: We had only day to work on these and try to do our best. We still want to see any respect and appreciation (not criticism). I want to thank my designer "Birol Vural" who is really talented. 
Regards..

**Version-1:**
![11](https://user-images.githubusercontent.com/25433115/38081557-ffcac84e-334c-11e8-87f1-c43b980abb2d.jpg)

**Version-2:**
![12](https://user-images.githubusercontent.com/25433115/38081610-1d3f512e-334d-11e8-80ee-07c271bd777e.jpg)

**Version-3:** (My favorite one)
![18](https://user-images.githubusercontent.com/25433115/38081641-339fa608-334d-11e8-9713-ded355a0558d.png)

**Our Submission:"
![version-top](https://user-images.githubusercontent.com/25433115/38081791-8e11ec2c-334d-11e8-8d29-014f2e9d20d2.jpg)

**Comment by keilw** [comment]
@mfevzikorkutata Thanks for explaining. I guess your submission may have been eliminated because it looked too close to a **Swastika** with one leg missing? ;-O
Like in India, ancient [Swastika symbols ](http://captaingini.com/en/2016/01/swastika-in-bali/) are not uncommon in Indonesia, I'm sure you also find some in Jakarta, but this logo has too much historical debt to use it anywhere else regardless of the direction.

**Comment by hs536** [comment]
No.7> The shape of "J" (for JakartaEE) is suggestive of a hook. We'll connect the various ship(service) by Jakarta EE. Also We'll pull up the traditional service to the cloud. This logo has those messages :)
![jakarta](https://user-images.githubusercontent.com/28645517/38088818-2ab98108-3398-11e8-8444-e34410abcc90.png)

**Comment by dblevins** [comment]
Poll is now closed and the official voting is now open! Cast your vote! Vote will be closed April 6th.

https://t.co/cfxT47xTyQ
