### ISSUE TITLE
Create a list of all Maven groupIds for EE4J projects

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/ee4j#27]
The EE4J projects will sooner or later have the need to publish SNAPSHOT version. 
We need to first figure out what is legally possible
Then get the correct permissions from Sonatype to push. 
We will have to wait for Oracle agreement to be in place.
Probably best to do this as a bulk operation rather than every project having to do this on their own.

Ivar will create an action item on GitHub for creating a list of all the group id’s that will be affected. Typically, org.glassfish, javax, net.java etc.

**Comment by ivargrimstad** [comment]
If projects use the Nexus plugin to release artifacts, projects does not need any special access.

Accounts set up and and handled by the Eclipse Webmaster

**Comment by ivargrimstad** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=530304

**Comment by starksm64** [comment]
What about projects like cdi, bean validation, batch and common annotations which are not hosted under Eclipse infrastructure? Is there a central document that tracks each current api artifacts coordinates and the mapping to their Jakarta coordinates?

**Comment by ivargrimstad** [comment]
I propose to close this issue with reference to [EE4J Wiki](https://wiki.eclipse.org/New_Maven_Coordinates)

**Comment by ivargrimstad** [comment]
No objections, so I'll close it for now.
