### ISSUE TITLE
Determine and document the minimum standard for a committer election merit statement

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/ee4j#29]
According to the Eclipse Development Process, in order for a committer election to be considered valid, a demonstration of merit is required. Generally, merit is demonstrated with publicly accessible links to tangible contributions by the nominee to the project in the nomination statement.

Any minimum measure of quantity and quality of those contributions is left to the discretion of the PMC. Having said that, there has to be some minimum that's greater than zero. Basically, we need at least some visible proof that the nominee understands the Eclipse Development Process and is a good fit with the project team. This is part of operating in an open and transparent manner; the demonstration of merit is open for all to see.

We need to setup requirements and decide what sort of minimum bar that we'd like to set for a merit statement. 

This should be documented.

**Comment by waynebeaton** [comment]
Let's be sure to include a note that the employment status of a nominee must not be a factor in a project role election.

**Comment by ivargrimstad** [comment]
Check what other PMCs are doing

**Comment by smillidge** [comment]
Can we move forward with this or close? Should be pretty trivial to document if we want or do we just refer to the EDP? At this stage I am happy to refer to the EDP and take each on a case by case basis as we build up our committers.

**Comment by bshannon** [comment]
I'm fine with just "winging it" for now, until people start to complain
"why were they promoted to Committer when they're clearly not qualified?"

**Comment by smillidge** [comment]
OK I will leave open until end of week and then close with "we will use EDP criteria"

**Comment by ivargrimstad** [comment]
We will use EDP criteria
