### ISSUE TITLE
How to handle signing keys

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/ee4j#30]
I've been looking to build up the CI/CD pipeline for concurrency api and ri and the goal install fails due to the lack of a signing key. What should projects use as a signing key to sign jars?

**Comment by m0mus** [comment]
It's a question to @eclipsewebmaster. Signing keys should by provided by your Jenkins instance (in settings.xml). We collected some information here: https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job

I am suggesting creating a bug on Eclipse issues tracker and discuss it directly with webmasters. Here is a link: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community

**Comment by smillidge** [comment]
Keys are provided during the Jenkins provisioning. Closing
