### ISSUE TITLE
Create a Release Review Checklist

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/ee4j#31]
The Eclipse Project Handbook has a [checklist](https://www.eclipse.org/projects/handbook/#checklist), but it's heavily rooted in the Eclipse Foundation's history of most projects building Eclipse Platform Plug-ins. If you ignore the bits about bundles and plug-ins, though, it's a pretty good start.

The EMO does a lot of the actual checking, but leans on the PMC to assess that the project is working within their scope, is following the rules of the EDP (the open source rules of engagement in particular), and is just generally doing the right sorts of things to develop community. 

It's up to the PMC to determine how to assess this before giving approval for a Release Review. Having a checklist that we can point to would be a valuable asset.

**Comment by smillidge** [comment]
I agree. I think we need input on the legals as well from the EMO on what needs to be put into API projects for the first GlassFish release. Given discussions on the PMC mailing list.

**Comment by ivargrimstad** [comment]
Start a discussion on the mailing list

**Comment by ivargrimstad** [comment]
We need to produce a concrete list of items to check for. E.g. 

- a reasonable description that can be published on jakarta.ee (README.md)
   - contribution, help to get started etc. consistency across projects

**Comment by smillidge** [comment]
I believe this is handled by the Jakarta EE spec process now which has extensive checklists e.g. https://github.com/jakartaee/specification-committee/blob/master/spec_review_checklist.md . I will close and if we need something different please reopen.
