### ISSUE TITLE
Module names for Jakarta EE implementation projects under EE4J

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/ee4j#35]
The *jakarta* namespace **must not** be used for implementation projects. Eclipse standard practices must be followed.

The PMC suggests `org.eclipse.*` as module names for the EE4J projects.

Please add comments and/or suggestions to this issue.

**Comment by MrinalKanti** [comment]
Shouldn't this be `org.eclipse.ee4j.*` to differentiate from other eclipse projects/implementations?

**Comment by joakime** [comment]
Note: `org.eclipse.jetty.*` is an implementation of both the `eclipse-ee4j/servlet-api` and `eclipse-ee4j/websocket-api` specs (pre-jakarta ATM)

**Comment by waynebeaton** [comment]
The standard practice is to use the project short name for Java packages e.g. org.eclipse.glassfish.*

We don't generally use the Top-Level Project identity in technical namespaces.

**Comment by bshannon** [comment]
This is only about JPMS module names, not package names.

**Comment by ggam** [comment]
Oh sorry, that makes sense

**Comment by MrinalKanti** [comment]
If its just for JPMS module names then why not just use `ee4j.*` ? I believe JavaFX uses a similar convention.

**Comment by ggam** [comment]
I think EE4J should remain mostly as "an implemention detail". EclipseLink
and Yasson for example moved to EE4J from another top level project.
Potentially other projects in the future might do it, or EE4J projects can
go out.

**Comment by m-reza-rahman** [comment]
I think this is mostly a no-brainer unless I am missing something. org.eclipse.* is fine.

**Comment by rhuan080** [comment]
I think org.eclipse.ee is good to use.

**Comment by bshannon** [comment]
One of the things we learned with Java EE is that the association with "EE" can blur over time so just like Wayne says we shouldn't include "ee4j" in the name, I would suggest that we not include "ee" in the name.

**Comment by rhuan080** [comment]
Yes @bshannon. You are correct in that. But I think we need refer that this project is about enterprise. With this, I suggest org.eclipse.enterprise. Can we use that?

**Comment by bshannon** [comment]
Why does it matter that it's "about enterprise"?  Many of these API are used standalone in
a very non-enterprise environment.

**Comment by rhuan080** [comment]
Because the main goal is provide solutions to enterprise, although it is used in a non-enterprise environment.

**Comment by karianna** [comment]
I think the world has moved away from 'enterprise', Jakarta EE / EE4J is
looking to the future which is both traditional enterprise and Cloud Native

Cheers,
Martijn

**Comment by m0mus** [comment]
Module names should be derived from Maven groupIds. The recommended Maven groupId for EE4J projects is `org.eclipse.<project-name>`. So, the module name should be also `org.eclipse.<project-name>`.

For example:

org.eclipse.jersey
org.eclipse.soteria

**Comment by joakime** [comment]
If a project has multiple artifacts, the Maven `groupId` will turn into a prefix for the Module name.

Most of the artifacts being produced already in the various eclipse-ee4j projects already have an OSGi bundle name declared.
Wouldn't it be nice if we could align the OSGi bundle name and the JPMS Module name?

Note that we cannot rely on using the existing OSGi bundle name as-is.
Unfortunately JPMS Module names have different syntax rules (eg: cannot use hyphens in the name for JPMS)

Eg:
* `org.glassfish.tyrus.bundles.websocket-ri-bundle` is OK for OSGi but the hyphens are not allowed on JPMS
* `org.glassfish.tyrus.bundles.websocket.ri.bundle` is OK for JPMS and OSGi.

**Comment by jodastephen** [comment]
[Modules are not artifacts](https://blog.joda.org/2017/04/java-se-9-jpms-modules-are-not-artifacts.html). So it is important to not let maven group/artifact names drive module names. (Yes there is a link, but module naming should start from the package name, not the artifactId).

The idea of using `org.eclipse.*` for Eclipse hosted implementations is good. As is the idea of omitting `ee` and `ee4j`.

The module names should really match the root package name as per my [naming recommendations](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html). So, IMO this issue should focus on package naming for implementations, with the module name dropping out by virtue of being the root package name.

**Comment by smillidge** [comment]
Given the Eclipse Foundation also owns the GlassFish trademark what is wrong with retaining org.glassfish?

**Comment by bshannon** [comment]
I agree.  It seems fine to use org.glassfish.

**Comment by smillidge** [comment]
Are we agreed on org.glassfish for implementation projects under EE4J that currently have those package names? I will close in 7 days if no more comments?

**Comment by smillidge** [comment]
OK org.glassfish should be used for implementation projects that currently have those package names.
