### ISSUE TITLE
Formating Rulesets for IDEs

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/ee4j#36]
It would be great if someone would find the time to donate some formatting ruleset files for IDEs, matching the [recommed formatting rules](https://github.com/eclipse-ee4j/ee4j/wiki/Code-Conventions). This makes it easier for hacking the code with the IDE of choice.

Thanks to @arjantijms for donating his Eclipse IDE configuration in 20c7b20. It would be great to receive such contributions for more IDEs! :-)

**Comment by mkarg** [comment]
@wesleyegberto Thanks a lot! Have you analyzed why this differences exist? Is that wrong in Eclipse, wrong in IntelliJ oder simply undefined by the EE4J rules?

**Comment by wesleyegberto** [comment]
Yes, here is the resume:

* IntelliJ
  * No option to set the rule "Maximum width for comments 120";
  * No option to set the rule "Keep empty method's braces in same line"  (following Sun's Java CC 6.4).

* Eclipse
  * No option to force braces in single line if/for/while, it needs to be defined in CleanUp profile.

**Comment by arjantijms** [comment]
@wesleyegberto Thanks for the analysis!

Yes, it's expected that not all IDEs have the exact same options. Likewise, there's some things in the EE4J convention that a formatter (of course) doesn't capture, like not using obscure abbreviations for variable names. Using things like `@Override` where they should be used are also not done by a formatter.

For Eclipse the additional CleanUp profile that you mentioned might be helpful. I don't know if IntelliJ has something like that, but I guess it does.

**Comment by ivargrimstad** [comment]
@wesleyegberto I suggest you create a PR and then let the PMC have a look at where it is convenient to put the rules. Whether it is in this repository or on the EE4J Wiki or someplace else.

**Comment by wesleyegberto** [comment]
Hi
I did the PR but it showing [Checks have failed: invalid Signed-off-by footers](https://dev.locationtech.org/eclipse-webhook/services/status_details.php?id=5c361980b8fbc).
[Here](https://github.com/wesleyegberto/ee4j/commit/007c3b62537563d63c48dbc400547f3ede6523be) is my signed commit.

**Comment by ivargrimstad** [comment]
done
