### ISSUE TITLE
Marnee

### ISSUE THREAD

**Issue by gerring** [eclipse-ee4j/ee4j#4]
Here's mine Wayne, it's from the female name Marnie:

"**Marnee**" or "**MarnEE**" or "**Eclipse Marnee**" if you need EF in the the name.
It is an acronym for:
Multi-tiered, applications reliable. networked. enterprise enabling.

Inspiration from the old JEE blurb which had:
large-scale, multi-tiered, scalable, reliable, and secure network applications.
in it.

Cheerio,

Matt

**Comment by waynebeaton** [comment]
I see that you've added this on #1. Closing.
