### ISSUE TITLE
Include license text as separate file

### ISSUE THREAD

**Issue by salmanfs815** [eclipse-ee4j/ee4j#40]
Having a separate license file is more convenient for packaging purposes.

**Comment by ivargrimstad** [comment]
Not sure what you mean with this?

**Comment by salmanfs815** [comment]
@ivargrimstad It is suggested by the Fedora Project that the license text should be in its own file [1].
I suggest moving the license from the copyright header of the POM to its own LICENSE file.
I have already packaged ee4j for Fedora [2].

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text
[2] https://src.fedoraproject.org/rpms/ee4j-parent

**Comment by ivargrimstad** [comment]
Thanks! I don't see the immediate value of packaging this particular project for Fedora though...

**Comment by salmanfs815** [comment]
EE4J is a build requirement for Java Mail [1] and JavaBeans Activation Framework [2]

[1] https://src.fedoraproject.org/rpms/javamail/blob/jmc/f/javamail.spec#_17
[2] https://src.fedoraproject.org/rpms/jaf/blob/jmc/f/jaf.spec#_20

**Comment by ivargrimstad** [comment]
Thanks again! I will add a LICENSE.txt file to the repo

**Comment by ivargrimstad** [comment]
Before merging the PR, we should compile a list of projects that need to configure license override in their respective pom's.

**Comment by smillidge** [comment]
@ivargrimstad are we covered with this now. I know the Jakarta EE 8 release drove nclusion of license files. I will close in 7 days if no more comments.
