### ISSUE TITLE
Structure and Clarify location of EE4J documentation

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/ee4j#43]
It is a little confusing where we document rules, suggestions etc. related to EE4J projects. 
We currently have it spread out a little between:

- https://www.eclipse.org/ee4j/
- https://wiki.eclipse.org/Category:Jakarta_EE
- https://github.com/eclipse-ee4j/ee4j/wiki
- https://github.com/eclipse-ee4j/ee4j

**Comment by bshannon** [comment]
I thought it was decided that, in general, it should be on wiki.eclipse.org,
and that pages from the GitHub ee4j wiki should be migrated there.  At
the very least, there should be links from pages on the Eclipse wiki to
information that might need to be stored elsewhere.

**Comment by ivargrimstad** [comment]
Yes, this item is probably more about communicating out links to the wiki and clean up a little where we have missed. There are still questions now and then on the mailing lists about where to find information.

**Comment by ivargrimstad** [comment]
Good for now
