### ISSUE TITLE
Publish Open Source Builds of the Jakarta EE TCK

### ISSUE THREAD

**Issue by dblevins** [eclipse-ee4j/ee4j#46]
There needs to be a channel for distributing builds of the Jakarta EE TCK.  Everyone is forced to build from source at the moment.  Eclipse GlassFish is currently building it from source.  Apache TomEE community is currently building it from source.

Note this is not a discussion of how the official final TCK build under the TCK license will be distributed.  This is simply establishing a distribution mechanism for projects to consume the TCK binaries in daily runs of the TCK to support what will be a several-month process of chasing compliance.

Ideally, it would be something that can be fetched in an automated fashion from a build job.

**Comment by ivargrimstad** [comment]
Nightly builds are published from the CI system. Work is ongoing to get github pages up for each project.

**Comment by ivargrimstad** [comment]
Done
