### ISSUE TITLE
Does the Wiki here make any more sense?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/ee4j#47]
Most of the Wiki pages under https://github.com/eclipse-ee4j/ee4j/wiki say "Moved to Eclipse Wiki", so does a "ghost" Wiki still make sense in this repository, or could it not be disabled?

**Comment by ivargrimstad** [comment]
Done

**Comment by arjantijms** [comment]
@keilw @ivargrimstad Do you know where https://github.com/eclipse-ee4j/ee4j/wiki/Code-Conventions went to?

I just wanted to reference this, but discovered it's seemingly nowhere to be found anymore.
