### ISSUE TITLE
Retire the project bootstrapping status page

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/ee4j#48]
The EE4J Project Bootstrapping page/chart is no longer particularly useful or interesting. Let's shut it down.

https://www.eclipse.org/ee4j/status.php

**Comment by ggam** [comment]
Please note that most old Java EE repositories link to that page for the status of the donation (see e.g. https://github.com/javaee/security-soteria)

Removing that page would break all those links. Would it be possible to redirect that page to some more useful place?

**Comment by waynebeaton** [comment]
Maybe the next stage is to remove the chart and replace it with a description of the overall plan and our current place in it. Specifically, that the next goal is to produce the Jakarta EE 8 specification and maybe a few bullet points that describe what has to happen to make that real. Thoughts?

**Comment by ggam** [comment]
Sounds great!

**Comment by will-lyons** [comment]
Agreed

**Comment by ivargrimstad** [comment]
Ivar will remove the page from the website.

**Comment by ivargrimstad** [comment]
I WILL do it...

**Comment by ivargrimstad** [comment]
PR created: https://github.com/eclipse-ee4j/ee4j-website/pull/69
