### ISSUE TITLE
Question: How did we release 1.0.6, but the code is still at 1.0.6-SNAPSHOT?

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/ee4j#62]
Something seems out of whack...  We have released version [1.0.6 of the parent pom](https://search.maven.org/artifact/org.eclipse.ee4j/project/1.0.6/pom), but the [actual file](https://github.com/eclipse-ee4j/ee4j/blob/master/parent/pom.xml) still has 1.0.6-SNAPSHOT.  The code should be at 1.0.7-SNAPSHOT, correct?  And, how did we get into this situation in the first place?

**Comment by pzygielo** [comment]
I tried to show it in #58 :smile:

**Comment by bshannon** [comment]
Did someone forget to merge in the release branch after doing the release?

**Comment by bshannon** [comment]
Yup, the 1.0.6-RELEASE branch needs to be merged and then deleted.
Don't we have these instructions written down somewhere?

**Comment by kwsutter** [comment]
> I tried to show it in #58 😄

Looks like you shouldn't have given up so easily...  ;-) You were on the right track...

**Comment by kwsutter** [comment]
> Yup, the 1.0.6-RELEASE branch needs to be merged and then deleted.
> Don't we have these instructions written down somewhere?

Probably two issues here...  1)  The expected process is not documented sufficiently.  And, 2) other teams don't use this separate branch idea.  Instead, as part of the jenkins build, the pom is automatically updated with the next SNAPSHOT version.  I know this is the way that MicroProfile does it, so there are multiple ways of advancing master to the next SNAPSHOT...

**Comment by kwsutter** [comment]
Taken care of now via PR #63 .  Thanks for the discussion!

**Comment by bshannon** [comment]
To be clear, the reason for the separate branch is that it allows you to correct mistakes.
You can push something to the staging repo, create the branch, do some testing, and
then discover that it's not right after all.  You can then destroy the branch, destroy the
staged artifacts, and do it all over again.

If the release process had updated the repo, you then would have to commit a "rollback"
change and try again.  It leaves the repo full of your mistakes.

Obviously either way will work, with different advantages and disadvantages.
