### ISSUE TITLE
Proper version of the maven-enforcer-plugin and where to specify it

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/ee4j#64]
While attempting to release the RC1 for the Platform and Web Profile APIs, I have the following warning in the output (this is repeated for everyone of our modules in the jakartaee-api repo):

```
[WARNING] Some problems were encountered while building the effective model for jakarta.platform:jakarta.jakartaee-bom:pom:9.0.0-RC1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /home/jenkins/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
```

Looking at the 1.0.6 version of the parent pom, I see that we don't specify a version for the maven-enforcer-plugin:

```
                     <groupId>org.apache.maven.plugins</groupId>
                     <artifactId>maven-enforcer-plugin</artifactId>
```

Are users of the the parent pom supposed to specify a version for this plugin?  It looks like most everybody follows this practice with the `maven-source-plugin` and specifies a version in their own pom files.  But, I thought one of the reasons of having a parent pom was to define which version is defined for the whole EE4J project -- and if a component needs override the version for some reason, then they can do that.

This isn't stop ship right now.  But, we should get this cleaned up to avoid these Warnings in our builds.

**Comment by kwsutter** [comment]
If we decide to specify the version for `maven-enforcer-plugin` in the parent pom, then we should do the same for `maven-source-plugin` and `maven-javadoc-plugin`.

FYI, it looks like `maven-enforcer-plugin` should be version 3.0.0-M3 (latest version from Nov 2019).  And, maybe `maven-source-plugin` should be 2.1 and `maven-javadoc-plugin` should be 3.1.0?  At least those are the versions used by jakartaee-api.

Do these type of updates warrant a 1.0.7 version of the parent pom, or should the users of the parent pom just specify the desired versions to avoid the warnings?

**Comment by pzygielo** [comment]
> FYI, it looks like `maven-enforcer-plugin` should be version 3.0.0-M3 (latest version from Nov 2019). And, maybe `maven-source-plugin` should be 2.1 and `maven-javadoc-plugin` should be 3.1.0? At least those are the versions used by jakartaee-api.

Hmm... #61

**Comment by lukasj** [comment]
I'm strongly against this kind of change unless someone shows easy way how to override the version defined by the parent in subprojects. See also https://github.com/eclipse-ee4j/ee4j/issues/22#issuecomment-388829924

**Comment by pzygielo** [comment]
> I'm strongly against this kind of change unless someone shows easy way how to override the version defined by the parent in subprojects. See also [#22 (comment)](https://github.com/eclipse-ee4j/ee4j/issues/22#issuecomment-388829924)

Shown in https://github.com/eclipse-ee4j/ee4j/pull/61#issuecomment-589298702.

**Comment by kwsutter** [comment]
> > FYI, it looks like `maven-enforcer-plugin` should be version 3.0.0-M3 (latest version from Nov 2019). And, maybe `maven-source-plugin` should be 2.1 and `maven-javadoc-plugin` should be 3.1.0? At least those are the versions used by jakartaee-api.
> 
> Hmm... #61

Doh!  Your PR #61 resolves this Issue.  Thanks!  My vote is to go ahead with your merge and then create the 1.0.7 version of the parent pom.  We can let the components know it's available for use, but it's not a required update.  Thoughts?

**Comment by lukasj** [comment]
@pzygielo right, this works. I only don't think gpg is nice example for the problem in place.

The thing is that when working locally, one typically does not need javadoc but sometimes need sources.
What I have now is sth like (and few dozens projects (modules/childs) inheriting from this):

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.7-SNAPSHOT</version>
    </parent>

    <groupId>com.github.eclipse-ee4j</groupId>
    <artifactId>ee4j-child</artifactId>
    <version>1-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.0.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

When I run `mvn verify` or `mvn verify -Poss-release` without your change, I get exactly same result in both cases:

```
[INFO] 
[INFO] --- maven-source-plugin:3.0.0:jar-no-fork (attach-sources) @ ee4j-child ---
[INFO] 
```

When I run both commands with you change, I get following for `mvn verify`:

```
[INFO] 
[INFO] --- maven-source-plugin:3.0.0:jar-no-fork (attach-sources) @ ee4j-child ---
```

and for `mvn verify -Poss-release`
```
[INFO] 
[INFO] --- maven-source-plugin:3.2.0:jar-no-fork (attach-sources) @ ee4j-child ---
[INFO] 
```

To get the same behaviour for both commands with your change, one has, IMO, basically two options:
- forget using plugin management section for these plugins
- redefine plugin version under the "overridden" version of the oss-release profile and keep it in sync with the one in pluginsManagement section

...been there, done that and I'm finding it too complicated to share some common plugin configuration between various executions, very error prone, especially for not so experienced people, and not so easy to troubleshoot when things go wrong. Therefore I still believe that it is better for each child of ee4j parent to define plugin versions explicitly itself.

Or is there other way I can define my own version of the plugin with your change, get consistent behaviour with and without `oss-release` profile and preferably do that on one place while still be able to inherit that config in child projects?

**Comment by kwsutter** [comment]
Okay, moving the proposed resolution from PR #61 to PR #65.  Thanks for the conversation!

**Comment by lukasj** [comment]
#65 works fine for my use-case and I'm OK with that. Only consider using latest versions of plugins being defined there (maven-source-plugin 3.2.1, maven-javadoc-plugin 3.2.0 - currently is 3.2.0/3.1.1)

**Comment by pzygielo** [comment]
@lukasj - thanks for checking. Plugins updated in #65.
