### ISSUE TITLE
Will Jakarta EE9 include module-info?

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/ee4j#67]
Hello! 
I would like to know if all specs (JPA, JTA, JAX-RS, ...) have a plan to include module-info to be Jakarta EE 9 compatible or if it's planned only for Jakarta EE 10+.

**Comment by ivargrimstad** [comment]
Jakarta EE 9 will not cover module-info. See the [Platform project pages](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9) for details.
