### ISSUE TITLE
Future EE4J project hierarchies and navigation

### ISSUE THREAD

**Issue by irobins** [eclipse-ee4j/ee4j#7]
We have agreed to start with a flat ee4j project structure, where all projects - including API and impl projects - are simply independent technology projects and any relationship or navigation between will rely on an overarching EE4J project web page.
As all the technologies for EE are moved to EE4J, including their APIs, RIs and TCKs, understanding the relationship between (for example) the JAX-RS API project and Jersey implementation project may become challenging without some form of project hierarchy. EE has always welcomed multiple implementations and it is certainly conceivable in the future that independent implementations of a single API may be managed under EE4J. That would not require project hierarchies but may benefit from them. Precedent for project hierarchies exists (e.g. https://projects.eclipse.org/projects/modeling.m2t) although it has not necessarily been shown to be useful in the past.

This issue is a placeholder for future discussion as we get more experience in EE4J - for now we are agreed on a non-hierarchical project structure.

**Comment by karianna** [comment]
A useful navigation can be to have a diagram showing the relationships in this repo as permanent doc.  It's worked well for us on the AdoptOpenJDK build farm (50 repo/projects and counting)

**Comment by ivargrimstad** [comment]
Diagram is created. Will be integrated in the website later.

**Comment by ivargrimstad** [comment]
https://www.eclipse.org/ee4j/relationships.php
