### ISSUE TITLE
Explain why the default licensing scheme was selected

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/ee4j#8]
The [EE4J Top-Level Project Charter](https://projects.eclipse.org/projects/ee4j/charter) states:

> Content produced by projects under the Eclipse EE4J Top Level Project is licensed under the Eclipse Public License v2.0, with the Secondary License GPL 2.0 with Classpath Exception. 

We should capture why.

**Comment by MrinalKanti** [comment]
I agree that we need to be very clear about why EE4J is using dual licensing and under what circumstances is this applicable and acceptable going forward. While this might be helpful for existing vendors to incorporate the new EE4J content with the same compatibility level as earlier versions of Java EE without having to investigate into a new license (which may further delay adoption).

On the other hand, this has the risk of letting developers select GPLv2 as the sole license for various new projects in the EE4J ecosystem. If I understand correctly, EPLv2 is incompatible with GPL and requires the initial contributors to explicitly consent for EPL [as per GNU](https://www.gnu.org/licenses/license-list.html#GPLIncompatibleLicenses).

> If an initial contributor releases a specific piece of code and designates GNU GPL version 2 or later as a secondary license, that provides explicit compatibility with those GPL versions for that code. (Doing so is roughly equivalent, for users, to releasing that piece of code under a dual license, EPL | GPL.) **However, the EPL2 without this designation remains incompatible with the GPL**.

I am not only referring to new projects directly under the EE4J or Whatchamacallit-EE, but a hurdle for incorporate existing(1) projects (with GPLv2) into them when their initial contributors are, lets just say, not around.

(1) existing here refers to new projects started hereafter and which gain maturity and popularity over a period of time and subsequently may benefit from being included into the EE4J

**Comment by srbala** [comment]
Projects under EE4J (@eclipse-ee4j) are subjected to dual licenseing. So any contributions to EE4J subjected to dual license.

Developers/Vendors creating any drived work based on EE4J projects, get to elect EPL or GPLV2 for their work.

**Comment by waynebeaton** [comment]
It is not strictly dual license. There's a bit of a subtlety at play.

https://www.eclipse.org/legal/epl-2.0/faq.php#h.lgjcpvoq08a9

> It is extremely close to dual licensing. The EPL-2.0 is the only license, until such time as it is combined and distributed with a work under the Secondary License. After such time, any recipient of the combined work can consider the content licensed under the Secondary License. The original work remains under the EPL-2.0 and is never really dual-licensed. Once a downstream adopter has received the content under the Secondary License, they can modify and further distribute it solely under the terms of the Secondary License.

FWIW, the SPDX license expression syntax doesn't have a means of specifying a "secondary license" and so we just structure it as dual licensing. This isn't too far off base since the SPDX licenses are expressed from the perspective of the consumer.

**Comment by karianna** [comment]
Is this not already covered in the FAQ?

**Comment by waynebeaton** [comment]
I don't think that the FAQ captures this directly, no.

**Comment by ivargrimstad** [comment]
FAQ: https://www.eclipse.org/ee4j/faq.php
Should probably be updated a little.

**Comment by smillidge** [comment]
@waynebeaton are you planning to update the FAQ or shall I close this as won't happen?

**Comment by waynebeaton** [comment]
I am not. I had hoped that those individuals involved with the decision to select the licensing scheme would provide us with a sentence or two.

**Comment by smillidge** [comment]
OK I will close this then.
