### ISSUE TITLE
Release 1.0.8 of parent pom

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/ee4j#83]
It's been a while since 1.0.7 and the updated versions in 1.0.8 are important for projects that wish to compile using JDK 17.

**Comment by pzygielo** [comment]
:+1: 
I hope this will be better heard than
- https://github.com/eclipse-ee4j/ee4j/pull/79#issuecomment-1287658387

**Comment by arjantijms** [comment]
ping @keilw @ivargrimstad

**Comment by arjantijms** [comment]
@pzygielo maybe the only real solution is to stop using this parent pom and just let each project have its own defined main / parent?

**Comment by pzygielo** [comment]
> maybe the only real solution is to stop using this parent pom and just let each project have its own defined main / parent?

I think such EE4J-level parent is a good place to keep rarely changing EF-infrastructure related configuration, like distribution management, staging/release profiles.
At this moment - I'd rather keep using it.

But to drop its usage is something to consider, for sure.

**Comment by ivargrimstad** [comment]
Done
